[abababab]
pwd = "my_socrates_note"
file = "abababab.html"

[babababa]
pwd = "montereys_coast"
file = "babababa.html"

[deadbeef]
pwd = "east_stormy_cones"
file = "deadbeef.html"

[feebdaed]
pwd = "too_many_secrets"
file = "feebdaed.html"