[memo]
pwd = "my_socrates_note"
file = "memo.html"

[liveforever]
pwd = "yates_moon_crest"
file = "liveforever.html"

[ocean]
pwd = "montereys_coast"
file = "ocean.html"

[deadbeef]
pwd = "too_many_secrets"
file = "deadbeef.html"